Description: |
  This stack uses a CloudFormation custom resource

Parameters:
  LambdaFunctionName:
    Type: String

Resources:
  # Use a custom resource
  CustomResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunctionName}"
      # Provide key/value pairs for parameters to the custom resource
      Parameter: Value
