Description: |
  Create a DynamoDB table using on demand billing.

Resources:

  # A DynamoDB Table
  CustomerTable:
    Type: AWS::DynamoDB::Table
    Metadata:
      Comment: A simple table that passes security scanner checks
      checkov:
        skip:
          - id: "CKV_AWS_119"
            comment: "SSEType KMS stores the key in the customer account"
      guard:
        SuppressedRules:
          - DYNAMODB_TABLE_ENCRYPTED_KMS
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS

