AWSTemplateFormatVersion: "2010-09-09"

Description: |
  This stack creates different EC2 Volumes

Parameters:
  KmsKeyId:
    Description: The KMS key master ID
    Type: String

Resources:
  # An EC2 volume
  Volume:
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !Select [0, Fn::GetAZs: !Ref "AWS::Region"]
      Encrypted: true
      KmsKeyId: !Ref KmsKeyId
      Size: 10
      VolumeType: gp2

  # An EC2 gp3 volume
  VolumeGp3:
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !Select [0, Fn::GetAZs: !Ref "AWS::Region"]
      Encrypted: true
      Iops: 3000
      KmsKeyId: !Ref KmsKeyId
      Size: 10
      Throughput: 125
      VolumeType: gp3

  # An EC2 io2 volume
  VolumeIo2:
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !Select [0, Fn::GetAZs: !Ref "AWS::Region"]
      Encrypted: true
      KmsKeyId: !Ref KmsKeyId
      Size: 10
      Iops: 100
      VolumeType: io2
