AWSTemplateFormatVersion: "2010-09-09"

Description: |
  This stack automates the creation of an AWS Launch Template

Parameters:
  LatestAmiId:
    Description: Region specific image from the Parameter Store
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  VpcId:
    Description: A VPC ID for the security group
    Type: AWS::EC2::VPC::Id

Resources:

  # A security group to be used by the launch template
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Auto scaling group security group
      VpcId: !Ref VpcId

  # An IAM role to be assumed by the ec2 service
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Actions:
          - sts:AssumeRole
      Path: "/"

  # The instance profile to be assumed by the instance
  IamProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref IamRole
      Path: "/"

  # A launch template
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-launch-template
      VersionDescription: A basic launch template
      LaunchTemplateData:
        EbsOptimized: true
        ImageId: !Ref LatestAmiId
        InstanceType: t3.micro
        IamInstanceProfile:
          Arn: !GetAtt IamProfile.Arn
        Monitoring:
          Enabled: true
        SecurityGroupIds:
          - !GetAtt SecurityGroup.GroupId
        MetadataOptions:
          HttpEndpoint: disabled
