Description: |
  Create a VPC with 2 subnets for the AWS Managed Microsoft AD with a password stored in secerets manager

Resources:
  # Create default tennacy VPC with DNS hostname and resolution support using RFC 1918 /24 subnet mask
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default

  # Create Private subnet in 1st available AZ with the first /26 subnet mask of the VPC CIDR
  VPCSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      CidrBlock: !Select
        - 0
        - Fn::Cidr:
            - !GetAtt VPC.CidrBlock
            - 2
            - 6
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC

  # Create Private subnet in 2nd available AZ with the second /26 subnet mask of the VPC CIDR
  VPCSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      CidrBlock: !Select
        - 1
        - Fn::Cidr:
            - !GetAtt VPC.CidrBlock
            - 2
            - 6
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC

  # Create a secret for AD
  AWSManagedADSecret:
    Type: AWS::SecretsManager::Secret
    Metadata:
      checkov:
        skip:
          - id: CKV_AWS_149
      guard:
        SuppressedRules:
          - SECRETSMANAGER_USING_CMK
          - SECRETSMANAGER_ROTATION_ENABLED_CHECK
    Properties:
      Description: 'Secret used for provisioning Managed AD'
      GenerateSecretString:
        PasswordLength: 24

  # Create AWS Managed Microsoft AD Enterpise Edition with a domain name of corp.example.com and NETBios name of CORP
  ManagedAD:
    Type: AWS::DirectoryService::MicrosoftAD
    Properties:
      CreateAlias: false
      Edition: Enterprise
      EnableSso: false
      Name: corp.example.com
      Password: !Sub '{{resolve:secretsmanager:${AWSManagedADSecret}}}'
      ShortName: CORP
      VpcSettings:
        SubnetIds:
          - !Ref VPCSubnet1
          - !Ref VPCSubnet2
        VpcId: !Ref VPC


